name: Test

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'Gemfile.lock'
      - '**/*.rb'
      - '.github/workflows/test.yml'

env:
  AWS_REGION: ap-northeast-1
  AWS_S3_BUCKET: "${{secrets.AWS_S3_BUCKET}}"
  AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
  AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
      fail-fast: true
      max-parallel: 1 # because conflict cache key
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run minitest
        run: bundle exec rake test
